### ISSUE TITLE
关于歌词

### ISSUE THREAD

**Issue by x1982** [zhheo/HeoMusic#10]
如果能让歌词始终处于垂直居中的位置，就是我见过最好的一款最好的在线播放器，希望作者努努力

**Comment by zhheo** [comment]
已优化

**Comment by x1982** [comment]
对不起，我之前没说清楚，我的本意是，当前高亮的那句歌词始终处于歌词容器的垂直居中那一行位置，目前来说，高亮始终处于第2行。按我的显示器高度，目前一共呈现了 10 行的歌词，让高亮这行处在第5行左右，就很完美了
