### ISSUE TITLE
关于每首歌都只能播放30秒

### ISSUE THREAD

**Issue by HaoranZing** [zhheo/HeoMusic#11]
是不是要vip的都不行呢？还是有什么方法可以获取全部歌曲？

**Comment by Superheroff** [comment]
> 是的，vip歌曲只能30s，这是版权商的限制
http://mobi.kuwo.cn/mobi.s?f=web&source=oppo&type=convert_url_with_sign&rid=228908&br=2000kflac
- 帮你解决这个议题

**Comment by zhheo** [comment]
建议使用本地播放的方式。使用2.0版本即可。
