### ISSUE TITLE
更新了歌单内容如何自动刷新

### ISSUE THREAD

**Issue by nicky1605** [zhheo/HeoMusic#14]
之前生成的一些QQ音乐的歌单里面发现大部分都是VIP歌单，造成无法播放。更新了歌单内容以后，刷新播放器跟重启Web服务都不能刷新HeoMusic的歌单列表。

**Comment by zhheo** [comment]
是缓存。你问到了并非我开发的部分的问题。metingjs的工作机制我也不太清楚。您可以考虑新建一个歌单如果比较着急的话。
