### ISSUE TITLE
能否新增一个本地曲库模式

### ISSUE THREAD

**Issue by aYuIsOK** [zhheo/HeoMusic#15]
使用服务商提供的api固然是方便，但是一些需要vip的歌曲就只能试听30s，并且对于applemusic用户更是难受，本地模式就可以把自己珍藏的一些无损资源放上去。希望可以

**Comment by echs-top** [comment]
附议

**Comment by zhheo** [comment]
2.0版本已支持

**Comment by sheerkvc** [comment]
> 使用服务商提供的api固然是方便，但是一些需要vip的歌曲就只能试听30s，并且对于applemusic用户更是难受，本地模式就可以把自己珍藏的一些无损资源放上去。希望可以

哥，有没有啥无损下载的地方呢，刚接触还不太了解，谢谢哈
