### ISSUE TITLE
可以多歌单吗，我自己整理的音乐有点多

### ISSUE THREAD

**Issue by echs-top** [zhheo/HeoMusic#16]

**Comment by zhheo** [comment]
可以建一个大歌单，将其他歌单音乐复制进去

**Comment by echs-top** [comment]
还是分开要好点，

**Comment by Asiprin** [comment]
// 定义服务器和歌单类型
  var userServer = "tencent";
  var userType = "playlist";

  // 定义多个歌单ID
  var playlistIds = ["9393114626","7496918367"];

  // 随机选取一个歌单ID
  var userId = playlistIds[Math.floor(Math.random() * playlistIds.length)];
