### ISSUE TITLE
大佬本地播放无法使用键盘控制，进度条需要歌曲完全缓存下来才能拖动

### ISSUE THREAD

**Issue by 1i4n** [zhheo/HeoMusic#18]
![image](https://github.com/zhheo/HeoMusic/assets/82950974/6344cbe2-9a70-46a5-b158-7945df38cb24)
![image](https://github.com/zhheo/HeoMusic/assets/82950974/c7cd026b-1b47-4be9-bec9-967fdf934b79)
![image](https://github.com/zhheo/HeoMusic/assets/82950974/83fa3486-18f0-4dbe-a787-3fb0a3b68c1e)

**Comment by zhheo** [comment]
我无法复现此问题。可以提供能复现的网址吗

**Comment by 1i4n** [comment]
> 我无法复现此问题。可以提供能复现的网址吗

http://123.57.194.142/
这个地址，跟我使用python 开http服务有关系吗

**Comment by zhheo** [comment]
2.3已修复

**Comment by 1i4n** [comment]
感谢大佬的辛勤付出
