### ISSUE TITLE
建议把歌词聚焦改到中间

### ISSUE THREAD

**Issue by wmz1024** [zhheo/HeoMusic#2]
![image](https://user-images.githubusercontent.com/82153828/218318810-041f2932-91b7-464d-bcf2-04d77b0cd813.png)

![image](https://user-images.githubusercontent.com/82153828/218318788-9a76d35a-b3e8-4e0f-97eb-e7fd578b5e0b.png)

我觉得这样可能更好一些，看起来更舒服一些。只需要 `translateY(?px);` 后面的值+200px就可以了

觉得不好直接close即可 😂

**Comment by zhheo** [comment]
从体验上来说，唱过的歌词显示的必要性不是很强。。市面上大多数音乐播放器也是这个逻辑。

**Comment by wmz1024** [comment]
嗯嗯
