### ISSUE TITLE
kugou

### ISSUE THREAD

**Issue by Lpdog-py** [zhheo/HeoMusic#6]
你好！酷狗的分享链接里面的id试了几个id都不行，想问问大佬是不是酷狗id有特殊的获取方式，酷狗的我喜欢歌单能否获取到id。
以下是我的几个歌单链接：
https://www.kugou.com/songlist/gcid_3zaynorkz2z0bf/?uid=577256490&chl=wechat&cover=http%3A%2F%2Fimge.kugou.com%2Fstdmusic%2F20221118%2F20221118083511423898.jpg&iszlist=1
------------------------------------------------------------------------------------------------------------------------------------------------------
https://www.kugou.com/songlist/gcid_3zaynorkzkz0a9/?uid=577256490&chl=wechat&iszlist=1

望大佬回复一下，thanks

**Comment by zhheo** [comment]
「我喜欢的音乐」并不是一个歌单哦。请使用酷狗的歌单，它的链接格式类似：https://www.kugou.com/yy/special/single/3947131.html
