### ISSUE TITLE
多个歌单一起加载

### ISSUE THREAD

**Issue by yichenblog** [zhheo/HeoMusic#7]
你好，能多个歌单一起加载吗

**Comment by zhheo** [comment]
不支持，目前也没有支持计划。建议单独建立一个歌单，然后将其他歌单的歌添加进来

**Comment by Asiprin** [comment]
// 定义服务器和歌单类型
  var userServer = "tencent";
  var userType = "playlist";

  // 定义多个歌单ID
  var playlistIds = ["9393114626","7496918367"];

  // 随机选取一个歌单ID
  var userId = playlistIds[Math.floor(Math.random() * playlistIds.length)];
